local qoi = require "lua-qoi"
local image1 = qoi.read("../images/lua_qoi.qoi")
local image2 = qoi.new(42, 50, 3)
local image3 = qoi.read("../images/lua_qoi.qoi")
local image4 = qoi.new(20, 20, 4)
--print(image1.width .. "x" .. image1.height .. " " .. image1.channels)
assert(image1.width == 512 and image1.height == 512 and image1.channels == 4)
image1:write("image1.qoi")
--print(image2.width .. "x" .. image2.height .. " " .. image2.channels)
assert(image2.width == 42 and image2.height == 50 and image2.channels == 3)
image2:write("image2.qoi")
--print(image3.width .. "x" .. image3.height .. " " .. image3.channels)
assert(image3.width == 512 and image3.height == 512 and image3.channels == 4)
image3:write("image3.qoi")
--print(image4.width .. "x" .. image4.height .. " " .. image4.channels)
assert(image4.width == 20 and image4.height == 20 and image4.channels == 4)
image4:write("image4.qoi")

os.remove("image1.qoi")
os.remove("image2.qoi")
os.remove("image3.qoi")
os.remove("image4.qoi")

print("multiple.lua successful.")